# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Global rules
windowrule = suppress_event maximize, match:class .*
windowrule = opacity 1 0.9, match:class .*

# Keep full opacity for video call apps
windowrule = opacity 1.0 override 1.0 override 1.0 override, match:class ^(discord)$
windowrule = no_dim on, match:class ^(discord)$
windowrule = opacity 1.0 override 1.0 override 1.0 override, match:title .*(Meet|Microsoft Teams).*
windowrule = no_dim on, match:title .*(Meet|Microsoft Teams).*

# App-specific rules
windowrule = stay_focused on, match:class (albert)
windowrule = border_color rgba(683B8211) rgba(683B8211) 45deg, match:class (Spotify)

# Window rules for xwayland bridge
windowrule {
  name = xwayland-bridge
  match:class = ^(xwaylandvideobridge)$
  opacity = 0.0 override
  no_anim = on
  no_initial_focus = on
  max_size = 1 1
  no_blur = on
}

# Scrolling layout for workspace 8
workspace = 8, layout:scrolling
