# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Waydroid rules - match initial Waydroid window and specific apps
windowrule = match:class ^(Waydroid)$, float on
windowrule = match:class ^(Waydroid)$, size 720 1280
windowrule = match:class ^(Waydroid)$, center on
windowrule = match:class ^(Waydroid)$, monitor DP-1

windowrule = match:class ^(waydroid\..*)$, float on
windowrule = match:class ^(waydroid\..*)$, size 720 1280
windowrule = match:class ^(waydroid\..*)$, center on
windowrule = match:class ^(waydroid\..*)$, monitor DP-1

# Scrolling layout for workspace 8
workspace = 8, layout:scrolling
